In [4]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

# 第一題：題目：給定一個矩陣m，裡面的值都大於0。請將矩陣m裡大於等於1的數字都變成1，小於1的變成0。

In [11]:
m = np.array([[0.1,1,0.2],[2,0.6,7]])
for i in range(m.shape[0]):
    for j in range(m.shape[1]):
        if m[i,j]>=1:
            m[i,j]=1
        elif m[i,j]<1:
            m[i,j]=0
print(m)

[[ 0.  1.  0.]
 [ 1.  0.  1.]]


# 第二題：有A,B,C三個班級，每班皆有10個學生，期中考結束後，老師希望計算各班級每位學生的加權平均成績。請隨機產生3個班級的成績單,每班10人,共五科,權重為weights=[0.25,0.25,0.25,0.15,0.10]。請算出班級加權平均成績，並以一個array輸出。

In [36]:
calss_A=np.random.randint(0,100,(10,5))
calss_B=np.random.randint(0,100,(10,5))
calss_C=np.random.randint(0,100,(10,5))
class_sub=["國文","英文","微積分","Python","數學"]
print("class_A",calss_A,"class_B",calss_B,"class_C",calss_C)
weights=[0.25,0.25,0.25,0.15,0.10]
#print("a",calss_a*weights)
#print("b",calss_b*weights)
#print("c",calss_c*weights)
#print("a",calss_a*weights+(calss_b*weights)+(calss_c*weights))
#print("group",class_group)
np.vstack((class_sub,weights*calss_A,weights*calss_B,weights*calss_C))

class_A [[50 29 11 81 79]
 [79 33 30 83 56]
 [78 32 54 73 46]
 [27 17 23 90 88]
 [96 66 48 45 12]
 [15 30 23 43 69]
 [67 35 40 58 65]
 [32 61 37 29 38]
 [37  6  3 38 50]
 [38 60 86 51 20]] class_B [[ 5 36 54 57  3]
 [36 95 47 98 59]
 [60 36 49 65 56]
 [76 63 15 37 41]
 [67 29 58 27 47]
 [76 27 92 13 19]
 [96 62 71 86 41]
 [56 13 18 35 13]
 [ 8 44 86 72 60]
 [32 27 66  2 12]] class_C [[24 87 80 51 94]
 [67 87 78 62 26]
 [97 84 37 17 32]
 [ 9 98 24 15 81]
 [ 0  2 51 73 23]
 [80 66 28 79 87]
 [73 52 59 17 49]
 [37 71 71 86  6]
 [56 67 47 39 72]
 [31 22 65 26 43]]


array([['國文', '英文', '微積分', 'Python', '數學'],
       ['12.5', '7.25', '2.75', '12.15', '7.9'],
       ['19.75', '8.25', '7.5', '12.45', '5.6000000000000005'],
       ['19.5', '8.0', '13.5', '10.95', '4.6000000000000005'],
       ['6.75', '4.25', '5.75', '13.5', '8.8'],
       ['24.0', '16.5', '12.0', '6.75', '1.2000000000000002'],
       ['3.75', '7.5', '5.75', '6.45', '6.9'],
       ['16.75', '8.75', '10.0', '8.7', '6.5'],
       ['8.0', '15.25', '9.25', '4.35', '3.8000000000000003'],
       ['9.25', '1.5', '0.75', '5.7', '5.0'],
       ['9.5', '15.0', '21.5', '7.6499999999999995', '2.0'],
       ['1.25', '9.0', '13.5', '8.549999999999999', '0.30000000000000004'],
       ['9.0', '23.75', '11.75', '14.7', '5.9'],
       ['15.0', '9.0', '12.25', '9.75', '5.6000000000000005'],
       ['19.0', '15.75', '3.75', '5.55', '4.1000000000000005'],
       ['16.75', '7.25', '14.5', '4.05', '4.7'],
       ['19.0', '6.75', '23.0', '1.95', '1.9000000000000001'],
       ['24.0', '15.5', '17.75', '12.9',

In [17]:
breakfast_list = ['古早味', '德合香', '布朗奇早餐', '星巴克', '小貓咪', '傳香飯糰', '米塔', '麥當勞', '摩斯', '7-11', '全家']
lunch_and_dinner_list = ['小公寓', '波波恰恰', '湯饌', '享窩咖啡', '湯包', '殺人魔王', '呷麵騎士', '提洛斯', '蝴蝶漾', '東京小城', '金鰭', '樂山', 'My麵屋', '李氏餐酒館', '里克', '水煎包', '憩賢樓', '高句麗', '魯智深', '敏忠', '大正亭', '阿里郎', '鬼匠', 'Juicy Bun', '滇味廚房']
high_price_list = ['星巴克', '摩斯', '小公寓', '享窩咖啡', '金鰭', '李氏餐酒館', '里克', 'Juicy Bun', '滇味廚房']
snack_list = ['豆花', '政大烤場', '丐幫滷味', '鹹水雞']

print(breakfast_list,lunch_and_dinner_list,high_price_list,snack_list,end=" ,")

['古早味', '德合香', '布朗奇早餐', '星巴克', '小貓咪', '傳香飯糰', '米塔', '麥當勞', '摩斯', '7-11', '全家'] ['小公寓', '波波恰恰', '湯饌', '享窩咖啡', '湯包', '殺人魔王', '呷麵騎士', '提洛斯', '蝴蝶漾', '東京小城', '金鰭', '樂山', 'My麵屋', '李氏餐酒館', '里克', '水煎包', '憩賢樓', '高句麗', '魯智深', '敏忠', '大正亭', '阿里郎', '鬼匠', 'Juicy Bun', '滇味廚房'] ['星巴克', '摩斯', '小公寓', '享窩咖啡', '金鰭', '李氏餐酒館', '里克', 'Juicy Bun', '滇味廚房'] ['豆花', '政大烤場', '丐幫滷味', '鹹水雞'] ,